### ISSUE TITLE
GUI error

### ISSUE THREAD

**Issue by e-sivertsen** [IELET1002-G2/The-Tesla-of-Zumo-Cars#20]
I zumo/main.ino er det bare "calibrate" og "line" som fungerer, de andre funksjonene kjører ikke.

Og dersom usb er koplet til forsvinner GUI etter at et program har fulført, og zumo blir inaktiv.

**Comment by espi3000** [comment]
Var dette eit problem i debug-fila òg? @e-sivertsen 
edit: Har du sjekka om det står noko i seriellmonitoren?

**Comment by e-sivertsen** [comment]
Nei, i debug filen funker de andre funksjonene.

Ikke noe spesielt som skjer i seriemonitoren, den sender bare ut "meny" meldingen. Prøvde å legge inn en serial melding i "casene" i switchen, men de blir ikke skrevet ut. Når jeg skriver ut config[0] til seriemonitoren gir den riktig tall, men den looper evig selv om den skulle kjørt enableForceConfig, så det ser ut som den aldri går inn i de casene av en eller annen grunn.

Edit:
Ser ut som problemet når den er koplet til usb bare dukker opp når man prøver å kjøre funksjonene som ikke funker, så det er sikkert et relatert problem.
Å gi komandoer via seriemonitior funker selv om skjermen er blank og knappene ikke virker.

**Comment by espi3000** [comment]
Seriellmonitoren og knapp/lcd er to separate GUI så berre ein av dei kan kjøre om gongen. Dette kan eg ordne i seinare, men det er ein del arbeid å få dei til å køyre samtidig. Så eg valgte å kode det slik at den favoriserer seriellmonitoren og clearer lcd'en viss usb'en blir kopla til.

Debug-fila og main-fila hadde identiske Interface-klassar når eg commita dei, så eg forstår ikkje heilt kor problemet ligger.

Har du prøvd å kjørt circle()?

**Comment by e-sivertsen** [comment]
Ja, har prøvd alle funksjonene. Calibrate og line kjører som normalt, slalom kommer inn i avstandsvelgeren men ikke lenger, de andre skjer det ingen ting hvis du velger. Menyen stopper og om man trykker A eller C skjer det ingen ting første gang, andre gang går menyen videre som vanlig, om man trykker på B igjen får man opp pause menyen.

**Comment by espi3000** [comment]
Fungerer main i gui-branchen?
