### ISSUE TITLE
Servoproblem

### ISSUE THREAD

**Issue by espi3000** [IELET1002-G2/The-Tesla-of-Zumo-Cars#29]
Trur det mangler nokon funksjonar for å få servoen til å fungere. Kan du fikse dette @vegardhs1 ?
https://github.com/madhephaestus/ESP32Servo/blob/master/examples/Knob/Knob.ino

**Comment by haavardok** [comment]
Fint om dette vert gjort, for då kan eg implementere naudsynte funksjonar i alarmsystemet :)
