### ISSUE TITLE
Temperatursensor

### ISSUE THREAD

**Issue by espi3000** [IELET1002-G2/The-Tesla-of-Zumo-Cars#31]
Temperatursensor ser ut til å gi veldig varierande, men konsistent for låge temperaturar. Har andre same opplevelsen?

**Comment by milgad1997** [comment]
jeg vet ikke om dere har sett det men jeg har addet " float temperature = (rawValue - 500) / 10" 
kan det være derfor?

**Comment by haavardok** [comment]
Ja, endringa di @milgad1997 har kome med.

Erfaringa mi med temperatursensoren @espi3000 er noko lik: Mine verdiar varierar kvart sekund gjerne med +- 5 grader og er stort sett for låge (ligg på rundt 22 og 10 grader), og nokon gangar viser den gjerne 35 grader eller noko i den dur. Sjå film eg sendte i gruppechatten. I tillegg er den nokon gangar veldig sensitiv om eg skubbar borti den på breadboardet. Då kan den gjerne hoppe til 200+ grader.

Eg skal prøve den på ein annan pinne og sjå om dette vil hjelpe.

**Comment by haavardok** [comment]
Ja, etter ein del feilsøking og googling, så har eg funne ut fylgjande:

1. Endringa som du la inn @milgad1997 er ikkje korrekt justert for ei 3.3 V spenningsforsyning med 4095 moglege verdiar. Riktig verdibehandling skal sjå slik ut: 
`float milliVolts = analogRead(inputPin) * (3300.0 / 4095.0);`
`float temperature = (milliVolts - 500.0) / 10.0;`

2. Pinnenummer skal ikkje ha noko å seie for avlesinga, pinne 34 skal fungere til føremålet. Eg tok fram eit multimeter og målte spenninga ut slik som omtala her: https://www.instructables.com/id/Temperature-Sensor-Tutorial/, og forsynte sensoren frå to AA batteri i serie. Då målte eg 0.93 V, så eg trur nok vertfall min sensor ikkje gir den rette verdien ut, difor har eg no målingar i 28 graderssiktet (har justert for at eg forsyner sensoren med 3.00 V). Sjå ny video i gruppechatten

3. Det er mange ulike stadar som brukar ulik tilkopling på sensoren, men eg har fylgt den som er gitt i Arduinodatabladet for kitet våra, og har sett at pinne 1 skal vere Vs og 3 GND. Pinne 1 er markert på side 1 i dette dokumentet: https://drive.google.com/file/d/1G2ym0gDrjWnFifsBGVPHtYHD1BLl9wHF/view. Du vil få rare avlesingar visst kopla omvendt (som eg har gjort før hehe).


EDIT: Sensoren vert veldig varm, (veldig varmt å ta på), noko som er rart sidan sensoren skal ha "low self-heating" som det står i databladet. Dersom eg held på sensoren (som eg då eigentleg skal varme opp), går temperaturen ned. Dersom eg snur sensoren 180 grader rundt vert den ikkje varm, men gir svært låge målingar.

**Comment by espi3000** [comment]
Helvette eg brant meg
edit: Beklager språket. Dette gir meining for eg fekk målingar på 120 grader etter endringane 🤣

**Comment by haavardok** [comment]
Uff, uff gløym alt til no!!!!!

EDIT PÅ EDIT PÅ EDIT:
Gi meg ein time til så skal eg ikkje spreie fake news

**Comment by espi3000** [comment]
På den positive sida ser det ut som `(3300.0 / 4095.0)` gav rett temp vertfall 😆

**Comment by haavardok** [comment]
Nei no har eg prøvt fleire pinnar, usboscilloskop osb. og finn ikkje kva som gjer at TMP36-en gir så ustabile verdiar ... Einaste eg kan seie er at den ikkje vert varm dersom Vs er kopla heilt til venstre dersom du ser på flatsida av sensoren ...

Dersom eg køyrer eit eksempel som berre skal hente verdi frå pinnen, så får eg ein stabil på 720, som er for lite, då eg måler ein verdi på 0,75 V. Eigentleg skal pinneverdien vere 825, så eg skjønar ikkje kvifor vi får ein lågare pinneverdi.

**Comment by espi3000** [comment]
Prøvde begge eksempla her på arduino: https://learn.adafruit.com/tmp36-temperature-sensor/using-a-temp-sensor. Første eksempelet gir rare verdiar slik som me opplever. Andre eksempelet fungerte kjempebra. Så det er nok noko med referansespenningo slik du har oppdaga. Eg veit ikkje om det finnes analogReference() på esp32 slik det gjer på arduino.

**Comment by haavardok** [comment]
Meiner du då dette er løysinga for ESP32-en også? 

Ser ikkje heilt kvifor endringa på referansa skal gje stabile målingar, einaste eg ser føre meg er at temperaturmålingsområdet vert som forventa.

**Comment by espi3000** [comment]
Det løyste problemet på arduino. Veit ikkje korleis ein kan løyse det på esp.

**Comment by haavardok** [comment]
Har fjerna `BlynkAlarmLED.on()` og `BlynkAlarmLED.off()` sidan desse skapte problem med sensoravlesinga på temp.sensoren. Sensoren fungerer som normalt no.

![source](https://user-images.githubusercontent.com/52386166/80232977-0ce70e80-8656-11ea-8d56-190b77a01ecc.gif)
