### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by espi3000** [IELET1002-G2/The-Tesla-of-Zumo-Cars#32]
Terminal printer "0" tilsynelatande tilfeldig sjølv om ein ikkje har sendt noko til ESP. Andre som opplever dette?

**Comment by haavardok** [comment]
Nei, ikkje at eg får "0". Har sett nokon gongar at der på éi line kan stå noko slikt som: "adjshjasd".

**Comment by espi3000** [comment]
Feil: virtualWrite() til terminal.

**Comment by haavardok** [comment]
Mykje lesestoff på denne repoen etter kvart 
![xt19UyT](https://user-images.githubusercontent.com/52386166/80224871-9db7ed00-864a-11ea-963e-ff919668a080.gif)
